# Generated by Django 4.0.3 on 2023-06-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
