# Generated by Django 4.0.3 on 2023-06-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0002_user_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
