# Generated by Django 4.0.3 on 2023-07-03 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0003_topic_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='userkey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
