# Generated by Django 4.0.3 on 2023-07-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0004_topic_userkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
    ]
