# Generated by Django 4.0.3 on 2023-07-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0005_user_tokens_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
