# Generated by Django 4.0.3 on 2023-07-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0006_potentialuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PotentialUser',
        ),
        migrations.AddField(
            model_name='user',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
