# Generated by Django 4.0.3 on 2023-07-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0007_delete_potentialuser_user_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default='AABBCC', max_length=7),
        ),
    ]
