# Generated by Django 4.0.3 on 2023-07-10 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0008_user_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='authorized',
        ),
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
        migrations.AddField(
            model_name='user',
            name='account_created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 18, 12, 10, 521451)),
        ),
    ]
