# Generated by Django 4.0.3 on 2023-07-22 23:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0009_remove_user_authorized_remove_user_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 23, 23, 31, 326740, tzinfo=utc)),
        ),
    ]
