# Generated by Django 4.0.3 on 2023-07-22 23:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0010_user_isadmin_alter_user_account_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 23, 26, 7, 459644, tzinfo=utc)),
        ),
    ]
