# Generated by Django 4.0.3 on 2023-07-22 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0011_alter_user_account_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
