# Generated by Django 4.2.3 on 2023-07-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0012_alter_user_account_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='rating',
            new_name='interest_factor',
        ),
    ]
