# Generated by Django 4.2.3 on 2023-07-25 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0013_rename_rating_topic_interest_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('userkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_knowledge_level', models.IntegerField(default=0)),
                ('subtopics', models.ManyToManyField(to='voyageapp.rawtopic')),
            ],
        ),
    ]
