# Generated by Django 4.2.3 on 2023-07-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0014_rawtopic_expedition'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expeditions',
            field=models.ManyToManyField(to='voyageapp.expedition'),
        ),
    ]
