# Generated by Django 4.2.3 on 2023-07-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0015_user_expeditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lessons_completed',
            field=models.IntegerField(default=0),
        ),
    ]
