# Generated by Django 4.2.3 on 2023-07-28 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0016_user_lessons_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=100)),
                ('userkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expedition',
            name='expedition_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RawTopic',
        ),
        migrations.AlterField(
            model_name='expedition',
            name='subtopics',
            field=models.ManyToManyField(to='voyageapp.chapter'),
        ),
    ]
