# Generated by Django 4.2.3 on 2023-07-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0017_chapter_expedition_expedition_name_delete_rawtopic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_name',
            field=models.CharField(max_length=222),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='expedition_name',
            field=models.CharField(max_length=109),
        ),
    ]
