# Generated by Django 4.2.3 on 2023-07-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0019_expedition_userkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expedition',
            old_name='subtopics',
            new_name='chapters',
        ),
    ]
