# Generated by Django 4.2.3 on 2023-07-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0020_rename_subtopics_expedition_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='lessons_completed',
            field=models.IntegerField(default=0),
        ),
    ]
