# Generated by Django 4.2.3 on 2023-07-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0021_expedition_lessons_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='chapters_completed',
            field=models.IntegerField(default=0),
        ),
    ]
