# Generated by Django 4.2.4 on 2023-08-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0023_message_mentorshippost_user_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='messages',
        ),
        migrations.AddField(
            model_name='user',
            name='messagesin',
            field=models.ManyToManyField(related_name='messages_received', to='voyageapp.message'),
        ),
        migrations.AddField(
            model_name='user',
            name='messagesout',
            field=models.ManyToManyField(related_name='messages_sent', to='voyageapp.message'),
        ),
    ]
